apiVersion: v1
kind: Service
metadata:
  name: timescale-connector
  namespace: {{ .Values.tenantNamespace }}
  labels:
    app: timescale-connector
spec:
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}     
  selector:
    app: timescale-connector
